name: integrated_martial_arts_trainer
description: A complete offline martial arts training app with exercises, diet plans, and a smart coach.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & Utilities
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  percent_indicator: ^4.2.3
  fl_chart: ^0.68.0
  
  # Core Packages
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  flutter_riverpod: ^2.5.1
  flutter_tts: ^4.0.2
  just_audio: ^0.9.37

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# --- هذا هو الإصلاح الحاسم ---
flutter:
  uses-material-design: true

  # يجب أن تعرف كل مجلدات الأصول هنا
  assets:
    - assets/data/
    - assets/images/
    - assets/images/karate/
    - assets/sounds/
    - assets/fonts/

  # ويجب أن تعرف الخطوط هنا
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
