name: integrated_martial_arts_trainer
description: A complete offline martial arts training app with exercises, diet plans, and a smart coach.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & Utilities - UPDATED
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  percent_indicator: ^4.2.3 # This was already up to date
  fl_chart: ^0.68.0        # UPDATED
  
  # Core Packages - UPDATED
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  flutter_riverpod: ^2.5.1
  flutter_tts: ^4.0.2
  just_audio: ^0.9.37

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Lints - UPDATED
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/exercises.json
    - assets/images/
    - assets/images/karate/
    #... all other asset folders
    - assets/sounds/
    - assets/fonts/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700


