name: fight_app
description: Martial arts training app with offline cache + TTS
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  video_player: ^2.7.0
  flutter_tts: ^3.8.3
  cupertino_icons: ^1.0.6

  # Added for local DB
  sqflite: ^2.2.8
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter_upgrade:
