name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Flutter APK
    runs-on: ubuntu-latest

    steps:
      # 1. نسخ الكود
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. تثبيت Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0' # غيرها لو مشروعك يستخدم نسخة تانية

      # 3. تثبيت الباكدجات
      - name: Install dependencies
        run: flutter pub get

      # 4. بناء APK نسخة Release
      - name: Build APK
        run: flutter build apk --release

      # 5. رفع APK كملف Artifact للتحميل
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
