name: Build, Analyze, Backup and AI Review

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3' # غيّر حسب الإصدار اللي بتستخدمه

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Create Backup Branch
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          BRANCH="backup-$(date +'%Y%m%d-%H%M%S')"
          git checkout -b $BRANCH
          git push origin $BRANCH

  ai-review:
    runs-on: ubuntu-latest
    needs: build-android
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Google Generative AI
        run: pip install google-generativeai

      - name: Run AI Review
        env:
          GOOGLE_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          python - <<'EOF'
          import os
          import google.generativeai as genai

          genai.configure(api_key=os.getenv("GOOGLE_API_KEY"))
          model = genai.GenerativeModel("gemini-1.5-flash")

          prompt = """
          راجع الكود في المشروع وابحث عن مشاكل أو تحسينات ممكنة.
          لو في أي أخطاء أو ممارسات سيئة في Flutter/Kotlin قولها.
          """
          response = model.generate_content(prompt)
          print("AI Review Output:\n", response.text)
          EOF
