name: Build Flutter App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # الخطوة 1: تحميل الكود من المستودع
      - name: Checkout code
        uses: actions/checkout@v4

      # الخطوة 2: تثبيت JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # الخطوة 3: تثبيت Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.22.2'

      # الخطوة 4: إنشاء هيكل Android إذا كان مفقوداً
      - name: Create Android structure
        run: |
          if [ ! -d "android" ] || [ ! -f "android/gradlew" ]; then
            echo "إنشاء هيكل Android جديد..."
            flutter create --platforms=android --org com.example temp_project
            cp -r temp_project/android .
            rm -rf temp_project
          fi

      # الخطوة 5: منح صلاحيات تنفيذ لملف gradlew
      - name: Make gradlew executable
        run: chmod +x android/gradlew

      # الخطوة 6: تثبيت dependencies
      - name: Get packages
        run: flutter pub get

      # الخطوة 7: بناء حزمة التطبيق
      - name: Build Android App Bundle
        run: flutter build appbundle

      # الخطوة 8: رفع الملف الناتج
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-bundle
          path: build/app/outputs/bundle/release/app-release.aab
