# اسم سير العمل: النسخة النهائية والمضمونة (الإصدار 2)
name: Final Guaranteed Flutter Build v2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Your Code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      # هذه هي الخطوة التي تم إصلاحها
      - name: Recreate Project Structure (The Clean Slate Method)
        run: |
          # حفظ الملفات الأساسية (الكود والحزم والأصول) في مكان آمن
          mkdir safe_place
          mv lib safe_place/
          mv pubspec.yaml safe_place/
          if [ -d "assets" ]; then mv assets safe_place/; fi
          
          # --- هذا هو الإصلاح الحاسم ---
          # مسح كل شيء آخر في المجلد الرئيسي لضمان بداية نظيفة
          # ls -a1 | grep -v -E "^\.$|^\.\.$|^\.git$|^\.github$|^safe_place$" | xargs rm -rf
          
          # إنشاء مشروع فلاتر جديد ونظيف في المجلد الحالي
          flutter create .
          
          # حذف المجلدات المؤقتة من المشروع الجديد
          rm -rf lib
          
          # استعادة ملفاتك الأساسية من المكان الآمن
          mv safe_place/* .
          rm -rf safe_place

      - name: Get Dependencies for New Structure
        run: flutter pub get

      - name: Grant Execute Permission for Gradlew
        run: chmod +x android/gradlew

      - name: Build Android App Bundle
        run: flutter build appbundle --release

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-bundle
          path: build/app/outputs/bundle/release/app-release.aab
