# اسم سير العمل: النسخة النهائية ذاتية الإصلاح
name: Self-Healing Flutter Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # الخطوة 1: تنزيل الكود الذي رفعته (فقط مجلد lib و pubspec.yaml)
      - name: Checkout Your Code
        uses: actions/checkout@v4

      # الخطوة 2: إعداد بيئة فلاتر
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      # الخطوة 3: (هذه هي الخطوة السحرية)
      # إنشاء مشروع فلاتر جديد ونظيف حول الكود الخاص بك
      # هذا سيقوم بإنشاء مجلدات android و ios حديثة وصحيحة
      - name: Recreate Project Structure
        run: |
          # إنشاء مشروع مؤقت
          flutter create temp_project
          # نقل قلب مشروعك (الكود والحزم) إلى المشروع النظيف
          mv lib temp_project/
          mv pubspec.yaml temp_project/
          # إذا كان لديك مجلد assets، انقله أيضًا
          if [ -d "assets" ]; then mv assets temp_project/; fi
          # استبدال كل شيء بالمشروع النظيف
          mv temp_project/* .
          rm -rf temp_project

      # الخطوة 4: تحميل الحزم والمكتبات للمشروع الجديد
      - name: Get Dependencies for New Structure
        run: flutter pub get

      # الخطوة 5: إعطاء صلاحية التنفيذ لملف Gradle (الذي تم إنشاؤه حديثًا)
      - name: Grant Execute Permission for Gradlew
        run: chmod +x android/gradlew

      # الخطوة 6: بناء نسخة الأندرويد النهائية
      - name: Build Android App Bundle
        run: flutter build appbundle

      # الخطوة 7: رفع الملف الناتج ليكون جاهزًا للتحميل
      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-bundle
          path: build/app/outputs/bundle/release/app-release.aab



