# اسم سير العمل: بناء AAB و APK (مُحدّث — لا يحذف مجلد android)
name: Build AAB and APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Get Dependencies
        run: flutter pub get

      - name: Build Android App Bundle (AAB)
        run: flutter build appbundle --release

      - name: Build Android APK
        run: flutter build apk --release

      - name: Upload Release Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-files
          path: |
            build/app/outputs/bundle/release/app-release.aab
            build/app/outputs/flutter-apk/app-release.apk
