name: Build Flutter Android App

# متى يتم تشغيله
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# المهام التي سيتم تنفيذها
jobs:
  build:
    # سيتم البناء على جهاز افتراضي بنظام أوبنتو
    runs-on: ubuntu-latest

    # الخطوات مرتبة
    steps:
      # الخطوة 1: تنزيل الكود من المستودع
      - name: Checkout repository code
        uses: actions/checkout@v4

      # الخطوة 2: إعداد بيئة جافا (مطلوبة للأندرويد)
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # الخطوة 3: إعداد فلاتر
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # الخطوة 4: جعل ملف Gradle قابلاً للتنفيذ
      - name: Make gradlew executable
        run: chmod +x android/gradlew
        
      # الخطوة 5: تحميل الحزم والمكتبات
      - name: Get Flutter dependencies
        run: flutter pub get

      # الخطوة 6: بناء نسخة الأندرويد النهائية
      - name: Build Android App Bundle
        run: flutter build appbundle

      # الخطوة 7: رفع الملف الناتج ليكون جاهزًا للتحميل
      - name: Upload release artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-bundle
          path: build/app/outputs/bundle/release/app-release.aab


