# اسم سير العمل: خطة التطهير النهائية
name: The Ultimate Clean Slate Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      # الخطوة 1: تنزيل الكود
      - name: Checkout Your Code
        uses: actions/checkout@v4

      # الخطوة 2: إعداد فلاتر
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      # الخطوة 3: إنشاء هيكل مشروع نظيف
      - name: Recreate Project Structure
        run: |
          # حفظ الملفات الأساسية
          mkdir safe_place
          mv lib safe_place/
          mv pubspec.yaml safe_place/
          if [ -d "assets" ]; then mv assets safe_place/; fi
          
          # إنشاء مشروع فلاتر جديد ونظيف
          flutter create .
          
          # حذف المجلدات المؤقتة من المشروع الجديد
          rm -rf lib
          
          # استعادة ملفاتك الأساسية
          mv safe_place/* .
          rm -rf safe_place

      # الخطوة 4: (هذه هي الخطوة الحاسمة)
      # ترقية فلاتر وتحديث كل الحزم إلى أحدث إصدار متوافق
      - name: Upgrade Dependencies to Latest Versions
        run: |
          flutter upgrade
          flutter pub upgrade --major-versions

      # الخطوة 5: إعطاء صلاحية التنفيذ لملف Gradle
      - name: Grant Execute Permission for Gradlew
        run: chmod +x android/gradlew

      # الخطوة 6: بناء نسخة الأندرويد النهائية
      - name: Build Android App Bundle
        run: flutter build appbundle --release

      # الخطوة 7: رفع الملف الناتج
      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-bundle
          path: build/app/outputs/bundle/release/app-release.aab

