# اسم سير العمل: النسخة النهائية والمضمونة
name: Final Guaranteed Flutter Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Your Code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      # هذه هي الخطوة التي تم إصلاحها
      - name: Recreate Project Structure (Fixed)
        run: |
          # إنشاء مشروع مؤقت جديد وسليم
          flutter create temp_project
          
          # --- هذا هو الإصلاح المهم ---
          # نحذف المجلدات الفارغة من المشروع الجديد أولاً
          rm -rf temp_project/lib
          rm -f temp_project/pubspec.yaml
          
          # الآن ننقل ملفاتك بأمان إلى المشروع الجديد
          mv lib temp_project/
          mv pubspec.yaml temp_project/
          if [ -d "assets" ]; then mv assets temp_project/; fi
          
          # نستبدل كل شيء بالمشروع النظيف
          mv temp_project/* .
          rm -rf temp_project

      - name: Get Dependencies for New Structure
        run: flutter pub get

      - name: Grant Execute Permission for Gradlew
        run: chmod +x android/gradlew

      - name: Build Android App Bundle
        run: flutter build appbundle --release

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-bundle
          path: build/app/outputs/bundle/release/app-release.aab
